import { Project, SourceFile } from 'ts-morph';
import { UiBaseBuilder } from './ui-base-builder.js';
import { type FileDefinition, type ModuleConfig } from '../../types.js';
import { Reconciler } from '../../reconciler.js';

export class AuthBuilder extends UiBaseBuilder {
  constructor(
    protected moduleName: string,
    protected config: ModuleConfig,
    protected modulePath: string,
  ) {
    super(moduleName, config, modulePath);
  }

  async build(project: Project, sourceFile: SourceFile | undefined): Promise<void> {
    this.loadUiConfig();

    // 1. Generate use-auth hook
    this.generateUseAuth(project);

    // 2. Generate AuthProvider
    this.generateAuthProvider(project);
  }

  private generateUseAuth(project: Project) {
    const file = project.createSourceFile('src/hooks/use-auth.tsx', '', { overwrite: true });

    const definition: FileDefinition = {
      header: this.getHeader(),
      imports: [
        {
          moduleSpecifier: 'react',
          namedImports: ['useContext', 'createContext'],
        },
        {
          moduleSpecifier: '@/lib/api',
          namedImports: ['UserModuleTypes'],
        },
      ],
      // We'll define Context here for simplicity scaffold
      variables: [
        {
          name: 'AuthContext',
          isExported: true,
          declarationKind: 'const',
          initializer: `createContext<{ user: UserModuleTypes.User | null, isLoading: boolean, login: (data: any) => void, logout: () => void } | null>(null)`,
        },
        {
          name: 'useAuth',
          isExported: true,
          declarationKind: 'const',
          initializer: `() => {
    const context = useContext(AuthContext);
    if (!context) {
        throw new Error('useAuth must be used within an AuthProvider');
    }
    return context;
}`,
        },
      ],
    };
    Reconciler.reconcile(file, definition);
  }

  private generateAuthProvider(project: Project) {
    const file = project.createSourceFile('src/components/providers/AuthProvider.tsx', '', {
      overwrite: true,
    });

    // We assume generic implementation that fetching user from /api/auth/me or similar
    // Using simplified logic for scaffold. User should implement 'api.auth.me', 'api.auth.login' etc.
    // Or generic useQuery support.

    const definition: FileDefinition = {
      header: this.getHeader(),
      imports: [
        {
          moduleSpecifier: 'react',
          namedImports: ['ReactNode', 'useState', 'useEffect'],
        },
        {
          moduleSpecifier: '@/hooks/use-auth',
          namedImports: ['AuthContext'],
        },
        {
          moduleSpecifier: '@/lib/api', // Assume API Client
          namedImports: ['api', 'UserModuleTypes'],
        },
      ],
      variables: [
        {
          name: 'AuthProvider',
          isExported: true,
          declarationKind: 'const',
          initializer: `({ children }: { children: ReactNode }) => {
    const [user, setUser] = useState<UserModuleTypes.User | null>(null);
    const [isLoading, setIsLoading] = useState(true);

    // Mock session check
    useEffect(() => {
        const checkSession = async () => {
            try {
                // Assuming 'api.auth.me' exists. 
                // The scaffolding puts this here as a placeholder.
                if (api.auth?.me) {
                    const session = await api.auth.me();
                    setUser(session);
                }
            } catch (e) {
                // Not logged in
            } finally {
                setIsLoading(false);
            }
        };
        checkSession();
    }, []);

    const login = async (data: any) => {
        // Implement login logic
    };

    const logout = async () => {
        // Implement logout logic
        setUser(null);
    };

    return (
        <AuthContext.Provider value={{ user, isLoading, login, logout }}>
            {children}
        </AuthContext.Provider>
    );
}`,
        },
      ],
    };
    Reconciler.reconcile(file, definition);
  }

  private getHeader(): string {
    return '// GENERATED CODE - DO NOT MODIFY\n// This file was generated by the AuthBuilder.';
  }
}
