import { Project, SourceFile } from 'ts-morph';
import { BaseBuilder } from './base-builder.js';
import { type FileDefinition, type ModuleConfig } from '../types.js';
import { Reconciler } from '../reconciler.js';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { parse } from 'yaml';
import { ts } from '../primitives/statements/factory.js';

export interface HookTemplateConfig {
  event: string;
  action: string;
  filter?: boolean;
}

export interface HooksConfig {
  hooks: HookTemplateConfig[];
}

export class HookBuilder extends BaseBuilder {
  private hooksConfig: HooksConfig = { hooks: [] };

  constructor(
    protected moduleName: string,
    protected config: ModuleConfig,
  ) {
    super();
  }

  async build(project: Project, sourceFile: SourceFile | undefined): Promise<void> {
    this.loadHooksConfig();
    if (this.hooksConfig.hooks.length === 0) return;

    // Group hooks by action name for files, or just one file per hook?
    // One file per hook is easier for the glob pattern in server-init.ts
    for (const hook of this.hooksConfig.hooks) {
      this.generateHookFile(project, hook);
    }
  }

  private loadHooksConfig() {
    const configPath = join(process.cwd(), 'modules', this.moduleName, 'hooks.yaml');
    if (existsSync(configPath)) {
      try {
        const content = readFileSync(configPath, 'utf8');
        this.hooksConfig = parse(content) as HooksConfig;
      } catch {
        console.warn(`[HookBuilder] Failed to parse hooks.yaml for ${this.moduleName}`);
      }
    }
  }

  private generateHookFile(project: Project, hook: HookTemplateConfig) {
    const fileName = `src/hooks/${hook.event.replace(/\./g, '-')}-${hook.action.replace(/\./g, '-')}.ts`;
    const file = project.createSourceFile(fileName, '', { overwrite: true });

    const method = hook.filter ? 'filter' : 'on';

    const definition: FileDefinition = {
      header: this.getHeader(),
      imports: [
        {
          moduleSpecifier: '@/lib/modules/hooks',
          namedImports: ['HookSystem'],
        },
      ],
      functions: [
        {
          name: 'init',
          isExported: true,
          isAsync: true,
          statements: [
            ts`HookSystem.${method}("${hook.event}", async (data: unknown) => {
        console.info(\`[Hook] ${hook.event} triggered action ${hook.action}\`);
        // TODO: Implement hook logic
        return data;
    });`,
          ],
        },
      ],
    };

    Reconciler.reconcile(file, definition);
  }

  private getHeader(): string {
    return '// GENERATED CODE - DO NOT MODIFY\n// This file was generated by the HookBuilder.';
  }

  protected getSchema(): FileDefinition {
    throw new Error('HookBuilder manages multiple files. Use build().');
  }
}
