import { Project, SourceFile } from 'ts-morph';
import { UiBaseBuilder } from '../ui/ui-base-builder.js';
import { type FileDefinition, type ModuleConfig } from '../../types.js';
import { Reconciler } from '../../reconciler.js';
import { toPascalCase, toKebabCase } from '../../../utils/string.js';
import { ts } from '../../primitives/statements/factory.js';

export class PageObjectBuilder extends UiBaseBuilder {
  constructor(
    protected moduleName: string,
    protected config: ModuleConfig,
    protected modulePath: string,
  ) {
    super(moduleName, config, modulePath);
  }

  async build(project: Project, sourceFile: SourceFile | undefined): Promise<void> {
    this.loadUiConfig();
    const models = this.resolveModels();

    for (const model of models) {
      const modelName = toPascalCase(model.name);
      this.generatePageObject(project, modelName);
    }
  }

  private generatePageObject(project: Project, modelName: string) {
    const className = `${modelName}Page`;
    const kebabName = toKebabCase(modelName);
    const fileName = `tests/e2e/pages/${className}.pom.ts`;

    const file = project.createSourceFile(fileName, '', { overwrite: true });

    const definition: FileDefinition = {
      header: this.getHeader(),
      imports: [
        {
          moduleSpecifier: '@playwright/test',
          namedImports: ['Page', 'Locator', 'expect'],
        },
      ],
      statements: [
        ts`export class ${className} {
    readonly page: Page;
    readonly table: Locator;
    readonly createButton: Locator;
    readonly form: Locator;

    constructor(page: Page) {
        this.page = page;
        this.table = page.getByTestId('${kebabName}-table');
        this.createButton = page.getByTestId('create-${kebabName}-button');
        this.form = page.getByTestId('${kebabName}-form');
    }

    async goto() {
        await this.page.goto('/${this.moduleName}/${kebabName}s');
    }

    async clickCreate() {
        await this.createButton.click();
    }

    async verifyTableVisible() {
        await expect(this.table).toBeVisible();
    }
}`,
      ],
    };
    Reconciler.reconcile(file, definition);
  }

  private getHeader(): string {
    return '// GENERATED CODE - DO NOT MODIFY\n// This file was generated by the PageObjectBuilder.';
  }
}
