import { Project, SourceFile } from 'ts-morph';
import { UiBaseBuilder } from '../ui/ui-base-builder.js';
import { type FileDefinition, type ModuleConfig } from '../../types.js';
import { Reconciler } from '../../reconciler.js';
import { toPascalCase } from '../../../utils/string.js';
import { ts } from '../../primitives/statements/factory.js';

export class StoryBuilder extends UiBaseBuilder {
  constructor(
    protected moduleName: string,
    protected config: ModuleConfig,
  ) {
    super(moduleName, config);
  }

  async build(project: Project, sourceFile: SourceFile | undefined): Promise<void> {
    this.loadUiConfig();
    const models = this.resolveModels();

    for (const model of models) {
      const modelName = toPascalCase(model.name);

      // Table Story
      this.generateTableStory(project, modelName);

      // Form Story
      this.generateFormStory(project, modelName);
    }
  }

  private generateTableStory(project: Project, modelName: string) {
    const componentName = `${modelName}Table`;
    const file = project.createSourceFile(`src/components/${componentName}.stories.tsx`, '', {
      overwrite: true,
    });

    const definition: FileDefinition = {
      header: this.getHeader(),
      imports: [
        {
          moduleSpecifier: 'react',
          namedImports: ['Meta', 'StoryObj'],
        },
        {
          moduleSpecifier: `./${componentName}`,
          namedImports: [componentName],
        },
      ],
      variables: [
        {
          name: 'meta',
          isExported: true,
          declarationKind: 'const',
          // Using generic meta type for simplicity in scaffold
          initializer: `{
    title: '${this.moduleName}/${componentName}',
    component: ${componentName},
    tags: ['autodocs'],
} satisfies Meta<typeof ${componentName}>`,
        },
        {
          name: 'Default',
          isExported: true,
          declarationKind: 'const',
          initializer: `{
    args: {
        // Mock props if needed
    }
} satisfies StoryObj<typeof ${componentName}>`,
        },
      ],
      statements: [ts`export default meta;`],
    };
    Reconciler.reconcile(file, definition);
  }

  private generateFormStory(project: Project, modelName: string) {
    const componentName = `${modelName}Form`;
    const file = project.createSourceFile(`src/components/${componentName}.stories.tsx`, '', {
      overwrite: true,
    });

    const definition: FileDefinition = {
      header: this.getHeader(),
      imports: [
        {
          moduleSpecifier: 'react',
          namedImports: ['Meta', 'StoryObj'],
        },
        {
          moduleSpecifier: `./${componentName}`,
          namedImports: [componentName],
        },
      ],
      variables: [
        {
          name: 'meta',
          isExported: true,
          declarationKind: 'const',
          initializer: `{
    title: '${this.moduleName}/${componentName}',
    component: ${componentName},
    tags: ['autodocs'],
} satisfies Meta<typeof ${componentName}>`,
        },
        {
          name: 'Create',
          isExported: true,
          declarationKind: 'const',
          initializer: `{
    args: {
        // default args
    }
} satisfies StoryObj<typeof ${componentName}>`,
        },
      ],
      statements: [ts`export default meta;`],
    };
    Reconciler.reconcile(file, definition);
  }

  private getHeader(): string {
    return '// GENERATED CODE - DO NOT MODIFY\n// This file was generated by the StoryBuilder.';
  }
}
