import { Project, SourceFile } from 'ts-morph';
import { UiBaseBuilder } from '../ui/ui-base-builder.js';
import { type FileDefinition, type ModuleConfig } from '../../types.js';
import { Reconciler } from '../../reconciler.js';
import { toPascalCase } from '../../../utils/string.js';
import { ts } from '../../primitives/statements/factory.js';

export class UiTestBuilder extends UiBaseBuilder {
  constructor(
    protected moduleName: string,
    protected config: ModuleConfig,
  ) {
    super(moduleName, config);
  }

  async build(project: Project, sourceFile: SourceFile | undefined): Promise<void> {
    this.loadUiConfig();
    const models = this.resolveModels();

    for (const model of models) {
      const modelName = toPascalCase(model.name);

      // Table Test
      this.generateTableTest(project, modelName);

      // Form Test
      this.generateFormTest(project, modelName);
    }
  }

  private generateTableTest(project: Project, modelName: string) {
    const componentName = `${modelName}Table`;
    const file = project.createSourceFile(`src/components/${componentName}.test.tsx`, '', {
      overwrite: true,
    });

    const definition: FileDefinition = {
      header: this.getHeader(),
      imports: [
        {
          moduleSpecifier: 'vitest',
          namedImports: ['describe', 'it', 'expect'],
        },
        {
          moduleSpecifier: '@testing-library/react',
          namedImports: ['render', 'screen'],
        },
        {
          moduleSpecifier: `./${componentName}`,
          namedImports: [componentName],
        },
      ],
      variables: [
        // We'll generate the test block differently or use statements
      ],
      statements: [
        ts`describe('${componentName}', () => {
    it('renders correctly', () => {
        render(<${componentName} />);
        // Basic assertion - assuming table has some header or content
        // expect(screen.getByRole('table')).toBeInTheDocument();
    });
})`,
      ],
    };
    Reconciler.reconcile(file, definition);
  }

  private generateFormTest(project: Project, modelName: string) {
    const componentName = `${modelName}Form`;
    const file = project.createSourceFile(`src/components/${componentName}.test.tsx`, '', {
      overwrite: true,
    });

    const definition: FileDefinition = {
      header: this.getHeader(),
      imports: [
        {
          moduleSpecifier: 'vitest',
          namedImports: ['describe', 'it', 'expect'],
        },
        {
          moduleSpecifier: '@testing-library/react',
          namedImports: ['render', 'screen'],
        },
        {
          moduleSpecifier: `./${componentName}`,
          namedImports: [componentName],
        },
      ],
      statements: [
        ts`describe('${componentName}', () => {
    it('renders form', () => {
        render(<${componentName} />);
        // expect(screen.getByRole('button', { name: /save/i })).toBeInTheDocument();
    });
})`,
      ],
    };
    Reconciler.reconcile(file, definition);
  }

  private getHeader(): string {
    return '// GENERATED CODE - DO NOT MODIFY\n// This file was generated by the UiTestBuilder.';
  }
}
